#############################################################################
# Makefile for building: ParticlePanic.app/Contents/MacOS/ParticlePanic
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  ParticlePanic.pro
# Template: app
# Command: /Users/Tom/Qt/5.5/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile ParticlePanic.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DMAC_OS_X_VERSION_MIN_REQUIRED=1060 -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/Library/Frameworks/SLD2_image.framework -I/Library/Frameworks/SDL2.framework/Headers -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers -I. -I../../../Qt/5.5/clang_64/mkspecs/macx-clang -F/Users/Tom/Qt/5.5/clang_64/lib
QMAKE         = /Users/Tom/Qt/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ParticlePanic1.0.0
DISTDIR = /Users/Tom/Documents/GitHubStuff/ParticlePanic/obj/ParticlePanic1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -F/Library/Frameworks -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -stdlib=libc++ -mmacosx-version-min=10.7 -Wl,-rpath,/Users/Tom/Qt/5.5/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/Tom/Qt/5.5/clang_64/lib -L/usr/local/lib -framework SDL2 -framework SDL2_image -framework OpenGL -framework AGL -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/Vec3.cpp \
		src/Mat3.cpp \
		src/Particle.cpp \
		src/World.cpp \
		src/Toolbar.cpp \
		src/ParticleProperties.cpp \
		src/Commands.cpp 
OBJECTS       = obj/main.o \
		obj/Vec3.o \
		obj/Mat3.o \
		obj/Particle.o \
		obj/World.o \
		obj/Toolbar.o \
		obj/ParticleProperties.o \
		obj/Commands.o
DIST          = ../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/c++11.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		ParticlePanic.pro include/Particle.h \
		include/Vec3.h \
		include/Mat3.h \
		include/World.h \
		include/Toolbar.h \
		include/ParticleProperties.h \
		include/Commands.h src/main.cpp \
		src/Vec3.cpp \
		src/Mat3.cpp \
		src/Particle.cpp \
		src/World.cpp \
		src/Toolbar.cpp \
		src/ParticleProperties.cpp \
		src/Commands.cpp
QMAKE_TARGET  = ParticlePanic
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = ParticlePanic.app/Contents/MacOS/ParticlePanic

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d ParticlePanic.app/Contents/MacOS/ || mkdir -p ParticlePanic.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ParticlePanic.pro ../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/c++11.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		ParticlePanic.pro \
		/Users/Tom/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/Tom/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile ParticlePanic.pro
../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.5/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.5/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.5/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.5/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.5/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.5/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.5/clang_64/mkspecs/features/c++11.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.5/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.5/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.5/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.5/clang_64/mkspecs/features/lex.prf:
ParticlePanic.pro:
/Users/Tom/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/Tom/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile ParticlePanic.pro

qmake_all: FORCE

ParticlePanic.app/Contents/PkgInfo: 
	@test -d ParticlePanic.app/Contents || mkdir -p ParticlePanic.app/Contents
	@$(DEL_FILE) ParticlePanic.app/Contents/PkgInfo
	@echo "APPL????" > ParticlePanic.app/Contents/PkgInfo
ParticlePanic.app/Contents/Resources/empty.lproj: 
	@test -d ParticlePanic.app/Contents/Resources || mkdir -p ParticlePanic.app/Contents/Resources
	@touch ParticlePanic.app/Contents/Resources/empty.lproj
	
ParticlePanic.app/Contents/Info.plist: 
	@test -d ParticlePanic.app/Contents || mkdir -p ParticlePanic.app/Contents
	@$(DEL_FILE) ParticlePanic.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.ParticlePanic,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,ParticlePanic,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.5/clang_64/mkspecs/macx-clang/Info.plist.app >ParticlePanic.app/Contents/Info.plist

all: Makefile \
		ParticlePanic.app/Contents/PkgInfo \
		ParticlePanic.app/Contents/Resources/empty.lproj \
		ParticlePanic.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents include/Particle.h include/Vec3.h include/Mat3.h include/World.h include/Toolbar.h include/ParticleProperties.h include/Commands.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/Vec3.cpp src/Mat3.cpp src/Particle.cpp src/World.cpp src/Toolbar.cpp src/ParticleProperties.cpp src/Commands.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r ParticlePanic.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

obj/main.o: src/main.cpp /Library/Frameworks/SDL2.framework/Headers/SDL.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_main.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_stdinc.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_config.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_platform.h \
		/Library/Frameworks/SDL2.framework/Headers/begin_code.h \
		/Library/Frameworks/SDL2.framework/Headers/close_code.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_config_macosx.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_assert.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_atomic.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_audio.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_error.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_endian.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_mutex.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_thread.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_rwops.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_clipboard.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_cpuinfo.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_events.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_video.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_pixels.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_rect.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_surface.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_blendmode.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_keyboard.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_keycode.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_scancode.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_mouse.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_joystick.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_gamecontroller.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_quit.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_gesture.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_touch.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_filesystem.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_haptic.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_hints.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_loadso.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_log.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_messagebox.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_power.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_render.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_system.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_timer.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_version.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_image.h \
		/usr/local/include/SDL2/SDL.h \
		/usr/local/include/SDL2/SDL_image.h \
		include/Vec3.h \
		include/Mat3.h \
		include/Particle.h \
		include/ParticleProperties.h \
		include/World.h \
		include/Toolbar.h \
		include/Commands.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/Vec3.o: src/Vec3.cpp include/Vec3.h \
		include/Mat3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Vec3.o src/Vec3.cpp

obj/Mat3.o: src/Mat3.cpp include/Mat3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Mat3.o src/Mat3.cpp

obj/Particle.o: src/Particle.cpp include/Particle.h \
		include/Vec3.h \
		include/Mat3.h \
		include/ParticleProperties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Particle.o src/Particle.cpp

obj/World.o: src/World.cpp include/World.h \
		include/Particle.h \
		include/Vec3.h \
		include/Mat3.h \
		include/ParticleProperties.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_main.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_stdinc.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_config.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_platform.h \
		/Library/Frameworks/SDL2.framework/Headers/begin_code.h \
		/Library/Frameworks/SDL2.framework/Headers/close_code.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_config_macosx.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_assert.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_atomic.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_audio.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_error.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_endian.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_mutex.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_thread.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_rwops.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_clipboard.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_cpuinfo.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_events.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_video.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_pixels.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_rect.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_surface.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_blendmode.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_keyboard.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_keycode.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_scancode.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_mouse.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_joystick.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_gamecontroller.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_quit.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_gesture.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_touch.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_filesystem.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_haptic.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_hints.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_loadso.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_log.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_messagebox.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_power.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_render.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_system.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_timer.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_version.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_image.h \
		/usr/local/include/SDL2/SDL.h \
		/usr/local/include/SDL2/SDL_image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/World.o src/World.cpp

obj/Toolbar.o: src/Toolbar.cpp include/Toolbar.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_main.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_stdinc.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_config.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_platform.h \
		/Library/Frameworks/SDL2.framework/Headers/begin_code.h \
		/Library/Frameworks/SDL2.framework/Headers/close_code.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_config_macosx.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_assert.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_atomic.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_audio.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_error.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_endian.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_mutex.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_thread.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_rwops.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_clipboard.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_cpuinfo.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_events.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_video.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_pixels.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_rect.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_surface.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_blendmode.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_keyboard.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_keycode.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_scancode.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_mouse.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_joystick.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_gamecontroller.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_quit.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_gesture.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_touch.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_filesystem.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_haptic.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_hints.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_loadso.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_log.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_messagebox.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_power.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_render.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_system.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_timer.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_version.h \
		/Library/Frameworks/SDL2.framework/Headers/SDL_image.h \
		/usr/local/include/SDL2/SDL.h \
		/usr/local/include/SDL2/SDL_image.h \
		include/World.h \
		include/Particle.h \
		include/Vec3.h \
		include/Mat3.h \
		include/ParticleProperties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Toolbar.o src/Toolbar.cpp

obj/ParticleProperties.o: src/ParticleProperties.cpp include/ParticleProperties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ParticleProperties.o src/ParticleProperties.cpp

obj/Commands.o: src/Commands.cpp include/Commands.h \
		include/World.h \
		include/Particle.h \
		include/Vec3.h \
		include/Mat3.h \
		include/ParticleProperties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Commands.o src/Commands.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

